### ISSUE TITLE
자식 윈도우가 포함된 윈도우를 닫을 때 오류발생

### ISSUE THREAD

**Issue by stzhyegeun** [stzyoonsik/YoonSik#1]
최종마무리 버전에서 

자식 윈도우가 포함된 윈도우를 닫을 때,  **Window**클래스의 **release**메서드에서 오류가 발생합니다. 

``` actionscript
private function release():void
{
    for(var i:int = 0; i<_vecChild.length; ++i)
    {
        _vecChild[i].removeEventListeners(TouchEvent.TOUCH);                    
        _vecChild[i].removeEventListener(TouchEvent.TOUCH, onAddedEvents);
        _vecChild[i].removeFromParent();
        _vecChild[i].removeChildren();
        _vecChild[i].dispose();
        _vecChild[i].parent.dispose(); // <- 여기서 에러 발생!!
        _vecChild[i].release();
    }
    trace(System.totalMemory / 1024);           
    System.gc();

    this.removeEventListeners(TouchEvent.TOUCH);
    this.removeEventListener(TouchEvent.TOUCH, onAddedEvents);
    this.removeFromParent();    
    this.removeChildren();
    this.dispose();         
}
```

원인이 무엇이고 어떻게 해결해야 할까요?

**Comment by stzyoonsik** [comment]
다시 2번 과제를 열어보니 _vecChild[i].parent.dispose(); 는 이미 제가 지웠었네요.. 최종 커밋 하는 과정에서 실수가 있었던 듯 싶습니다.. 죄송합니다. 에러의 원인은 이미 부모윈도우가 삭제된 상태여서, parent에 null이 들어와서가 아닐까 생각합니다.

**Comment by stzhyegeun** [comment]
넵. 추가적으로 한번 보시면 좋을 만한 링크 남깁니다.
[효과적인 스프라이트 메모리 관리](http://stackoverflow.com/questions/7056181/most-efficent-method-for-removing-children-from-a-displayobject-in-as3-memory)
요약하자면
- removeChild나 removeChildAt을 이용하여 디스플레이 리스트에서 제거
- 이벤트 리스너 전부 제거
- Array, Vector, Dictionary에서 참조하고 있다면 구조체에서 오브젝트 제거 
  - 해당 요소에 null을 할당하거나 
  - Array.splice() 사용
- 오브젝트 자체를 null로 할당

**Comment by stzyoonsik** [comment]
감사합니다 (__)
